MODEL: TensorFlowNN

INPUT_NAME: FwdMatchTrainingTree.root

OUTPUT_NAME:
 ORIGIN: tfNN.pkl
 ONNX: model.onnx

DEBUG_MODE:
 SHOW_RESULT: 1
 SHOW_PLOT: 0
 EXPORT_TXT: 1

SETUP_PARAMS:
 TEST_SIZE: 0.1
 EVAL_SIZE: 0.1
 TEST_SEED: 1
 EVAL_SEED: 1

HYPER_PARAM:
 TYPE: gbdt
 OBJECTIVE: binary
 LEARN_RATE: 0.0005
 METRIC: auc
 EPOCHS: 500
 BATCH_SIZE: 32
 VERBOSE: 1
 VALIDATION_SPLIT: 0.2

STRUCTURE:
  modelA:
    []
  modelB:
    []
  modelM:
    []

LOAD_PARAMS:
 - MFT_X
 - MFT_Y
 - MFT_Phi
 - MFT_Tanl
 - MFT_InvQPt
 - MCH_X
 - MCH_Y
 - MCH_Phi
 - MCH_Tanl
 - MCH_InvQPt
 - MFT_TrackChi2
 - MFT_NClust
 - MatchingChi2
 - Truth

CALC_PARAMS:
 Delta_X:
  - MFT_X
  - MCH_X
 Delta_Y:
  - MFT_Y
  - MCH_Y
 Delta_Phi:
  - MFT_Phi
  - MCH_Phi
 Delta_Tanl:
  - MFT_Tanl
  - MCH_Tanl
 Delta_InvQPt:
  - MFT_InvQPt
  - MCH_InvQPt

TRAIN_PARAMS:
 - MFT_X
 - MCH_X
 - MFT_Y
 - MCH_Y
 - MFT_Phi
 - MCH_Phi
 - MFT_Tanl
 - MCH_Tanl
 - MFT_InvQPt
 - MCH_InvQPt
 - MFT_TrackChi2
 - Delta_X
 - Delta_Y
 - Delta_Phi
 - Delta_Tanl
 - Delta_InvQPt

OBJECT:
 - Truth